name: Makefile CI

on:
  push:
    branches: [ master, build-tests ]
    tags: [ '*' ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  PD_VERSION: 0.56-2

jobs:
  ubuntu-amd64-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        floatsize: [32, 64]

    steps:
    - uses: actions/checkout@v7
      with:
        submodules: recursive
        fetch-depth: 0

    - name: install dependencies
      run: git clone --branch=$PD_VERSION --depth=1 https://github.com/pure-data/pure-data.git

    - name: make
      run: make install PDDIR=./pure-data objectsdir=./build floatsize=${{ matrix.floatsize }} extension=linux-amd64-${{ matrix.floatsize }}.so

    - name: upload
      uses: actions/upload-artifact@v7
      with:
        name: pdlua-ubuntu-amd64-pd${{ matrix.floatsize }}
        path: build

  ubuntu-arm64-build:
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        floatsize: [32, 64]

    steps:
    - uses: actions/checkout@v7
      with:
        submodules: recursive
        fetch-depth: 0

    - name: install dependencies
      run: git clone --branch=$PD_VERSION --depth=1 https://github.com/pure-data/pure-data.git

    - name: make
      run: make install PDDIR=./pure-data objectsdir=./build floatsize=${{ matrix.floatsize }} extension=linux-arm64-${{ matrix.floatsize }}.so

    - name: upload
      uses: actions/upload-artifact@v7
      with:
        name: pdlua-ubuntu-arm64-pd${{ matrix.floatsize }}
        path: build

  macos-universal-build:
    runs-on: macos-latest
    strategy:
      matrix:
        floatsize: [32, 64]

    steps:
    - uses: actions/checkout@v7
      with:
        submodules: recursive
        fetch-depth: 0

    - name: install dependencies
      run: |
        wget https://github.com/pure-data/pure-data/archive/refs/tags/$PD_VERSION.zip
        unzip $PD_VERSION.zip

    - name: make
      run: make install objectsdir=./build PDDIR=./pure-data-$PD_VERSION arch="arm64 x86_64" floatsize=${{ matrix.floatsize }} extension=darwin-fat-${{ matrix.floatsize }}.so

    - name: upload
      uses: actions/upload-artifact@v7
      with:
        name: pdlua-macos-universal-pd${{ matrix.floatsize }}
        path: build

  windows-amd64-build:
    runs-on: windows-latest
    strategy:
      matrix:
        floatsize: [32, 64]
    env:
      CC: gcc

    steps:
    - uses: actions/checkout@v7
      with:
        submodules: recursive
        fetch-depth: 0

    - name: setup MSYS2 MINGW64
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: mingw-w64-x86_64-gcc make

    - name: install Pure Data
      shell: pwsh
      run: |
        $id = (${{ matrix.floatsize }} -eq 64) ? "MillerPuckette.Pd64" : "MillerPuckette.PureData"
        $dir = (${{ matrix.floatsize }} -eq 64) ? "Pd64" : "Pd"
        winget install --id $id --exact --version $env:PD_VERSION --silent --accept-package-agreements --accept-source-agreements --disable-interactivity
        "PD_HOME=$env:ProgramFiles\$dir" | Out-File -FilePath $env:GITHUB_ENV -Append

    - name: make
      shell: msys2 {0}
      run: |
        pd_home=$(cygpath -u "$PD_HOME")
        make install objectsdir=./build PDINCLUDEDIR="$pd_home/src" PDBINDIR="$pd_home/bin" floatsize=${{ matrix.floatsize }} extension=windows-amd64-${{ matrix.floatsize }}.dll

    - name: upload
      uses: actions/upload-artifact@v7
      with:
        name: pdlua-windows-amd64-pd${{ matrix.floatsize }}
        path: build

# Big thanks to @tomara-x and @timothyschoen for showing me how to do this! -ag

  github-release:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    needs: [ubuntu-amd64-build, ubuntu-arm64-build, macos-universal-build, windows-amd64-build]

    steps:
    - uses: actions/download-artifact@v8

    - name: ziptie
      run: |
        mkdir dist
        for x in pdlua-*; do (cd $x && zip -r ../dist/$x.zip pdlua/); done

    - name: release
      uses: softprops/action-gh-release@v3
      with:
        prerelease: true
        draft: true
        files: dist/*.zip

  merge-for-deken:
    runs-on: ubuntu-latest
    needs: [github-release]
    permissions:
      contents: write
      actions: read
    strategy:
      matrix:
        os: [windows, macos, ubuntu]

    steps:
    - name: download artifacts # FIXME: currently downloads all artifacts redundantly for each OS
      uses: actions/download-artifact@v8
      with:
        path: artifacts

    - name: merge artifacts to package
      run: cp -rn artifacts/pdlua-${{ matrix.os }}*/* .

    - name: upload package
      uses: actions/upload-artifact@v7
      with:
        name: pdlua-${{ matrix.os }}
        path: pdlua

  deken-check:
    runs-on: ubuntu-latest
    needs: [merge-for-deken]
    strategy:
      matrix:
        os: [windows, macos, ubuntu]

    steps:
    - uses: actions/download-artifact@v8
      with:
        name: pdlua-${{ matrix.os }}
        path: pdlua-${{ matrix.os }}

    - name: check deken package
      shell: bash
      run: |
        echo "## ${{ matrix.os }}" | tee -a $GITHUB_STEP_SUMMARY
        mkdir -p package-${{ matrix.os }}
        docker run --rm --user $(id -u) --volume ./pdlua-${{ matrix.os }}:/pdlua \
          --volume ./package-${{ matrix.os }}:/package registry.git.iem.at/pd/deken \
          deken package --output-dir /package -v "${{ github.ref_name }}" /pdlua

        dek_files=$(ls package-${{ matrix.os }}/*.dek)
        for dek_file in $dek_files; do
          filename=$(basename "$dek_file")
          echo -e "#### \`$filename\`" | tee -a $GITHUB_STEP_SUMMARY
          echo '```' | tee -a $GITHUB_STEP_SUMMARY
          unzip -l "$dek_file" | awk 'NR>3 {print $4}' | sed '/^$/d' | sort | tee -a $GITHUB_STEP_SUMMARY
          echo '```' | tee -a $GITHUB_STEP_SUMMARY
        done

  deken-upload:
    if: ${{ !contains(github.ref, 'test') }} # upload if not a "test" tag (maybe should be more restrictive?)
    runs-on: ubuntu-latest
    needs: [merge-for-deken]
    steps:
    - uses: actions/checkout@v7
      with:
        path: pdlua-src

    - uses: actions/download-artifact@v8
      with:
        name: pdlua-windows
        path: pdlua-windows

    - uses: actions/download-artifact@v8
      with:
        name: pdlua-macos
        path: pdlua-macos

    - uses: actions/download-artifact@v8
      with:
        name: pdlua-ubuntu
        path: pdlua-ubuntu

    - name: upload deken package
      shell: bash
      env:
        DEKEN_USERNAME: ${{ secrets.DEKEN_USERNAME }}
        DEKEN_PASSWORD: ${{ secrets.DEKEN_PASSWORD }}
      run: |
        for os in ubuntu macos windows; do
          docker run --rm -e DEKEN_USERNAME -e DEKEN_PASSWORD \
            --volume ./pdlua-${os}:/pdlua registry.git.iem.at/pd/deken \
            deken upload --no-source-error -v "${{ github.ref_name }}" /pdlua
        done
        docker run --rm -e DEKEN_USERNAME -e DEKEN_PASSWORD \
          --volume ./pdlua-src:/pdlua registry.git.iem.at/pd/deken \
          deken upload -v "${{ github.ref_name }}" /pdlua
